-- ConTrack Phase 1 — run in Supabase SQL Editor (PostgreSQL)
-- Creates core tables if missing, then applies additive upgrades (idempotent).
-- Telemetry: last_login_at / last_seen_at updated by PHP on login and heartbeat.

-- -----------------------------------------------------------------------------
-- 1) Core tables (greenfield / empty project)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL DEFAULT '',
  email text NOT NULL,
  password text NOT NULL DEFAULT '',
  role text NOT NULL DEFAULT 'client',
  contact_number text,
  supplier_type text,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_login_at timestamptz,
  last_seen_at timestamptz,
  is_disabled boolean NOT NULL DEFAULT false,
  CONSTRAINT users_email_unique UNIQUE (email)
);

-- id is uuid: api/contract_pdf.php, nlp_usage.contract_id, and the portal JS all treat
-- contract ids as opaque strings.
CREATE TABLE IF NOT EXISTS public.vendor_contracts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vendor_id bigint REFERENCES public.users (id) ON DELETE CASCADE,
  vendor_name text,
  contract_title text NOT NULL DEFAULT '',
  contract_type text,
  contract_value numeric,
  start_date date,
  end_date date,
  payment_terms text,
  scope_of_work text,
  status text NOT NULL DEFAULT 'pending',
  uploaded_at timestamptz,
  source_file_name text,
  file_name text,
  file_path text,
  currency text DEFAULT 'PHP',
  reviewed_at timestamptz,
  reviewed_by text,
  ceo_notes text,
  manager_notes text,
  recommended_action text,
  manager_reviewed_at timestamptz,
  manager_reviewed_by bigint REFERENCES public.users (id) ON DELETE SET NULL
);

-- -----------------------------------------------------------------------------
-- 2) Additive upgrades (existing DBs that predate this file)
-- -----------------------------------------------------------------------------
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS last_login_at timestamptz,
  ADD COLUMN IF NOT EXISTS last_seen_at timestamptz,
  ADD COLUMN IF NOT EXISTS is_disabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS contact_number text,
  ADD COLUMN IF NOT EXISTS supplier_type text,
  ADD COLUMN IF NOT EXISTS terms_accepted_at timestamptz,
  ADD COLUMN IF NOT EXISTS terms_version text,
  ADD COLUMN IF NOT EXISTS company_name text,
  ADD COLUMN IF NOT EXISTS notify_alerts boolean NOT NULL DEFAULT true;

ALTER TABLE public.vendor_contracts
  ADD COLUMN IF NOT EXISTS manager_notes text,
  ADD COLUMN IF NOT EXISTS recommended_action text,
  ADD COLUMN IF NOT EXISTS manager_reviewed_at timestamptz,
  ADD COLUMN IF NOT EXISTS manager_reviewed_by bigint REFERENCES public.users (id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS ceo_notes text,
  ADD COLUMN IF NOT EXISTS file_name text,
  ADD COLUMN IF NOT EXISTS file_path text,
  ADD COLUMN IF NOT EXISTS currency text DEFAULT 'PHP',
  ADD COLUMN IF NOT EXISTS original_pdf_stored boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS submission_text text;

-- -----------------------------------------------------------------------------
-- 3) Indexes
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_users_last_seen_at ON public.users (last_seen_at DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_users_role ON public.users (role);
CREATE INDEX IF NOT EXISTS idx_users_email_lower ON public.users (lower(email));

CREATE INDEX IF NOT EXISTS idx_vendor_contracts_status ON public.vendor_contracts (status);
CREATE INDEX IF NOT EXISTS idx_vendor_contracts_manager_reviewed_by ON public.vendor_contracts (manager_reviewed_by);
CREATE INDEX IF NOT EXISTS idx_vendor_contracts_vendor_id ON public.vendor_contracts (vendor_id);
CREATE INDEX IF NOT EXISTS idx_vendor_contracts_manager_reviewed_at ON public.vendor_contracts (manager_reviewed_at);

-- Workflow statuses. Archiving uses the is_archived flag, never a status value.
ALTER TABLE public.vendor_contracts DROP CONSTRAINT IF EXISTS vendor_contracts_status_check;
ALTER TABLE public.vendor_contracts ADD CONSTRAINT vendor_contracts_status_check CHECK (
  status IN ('pending', 'approved', 'rejected', 'terminated', 'renegotiation', 'modification')
);

-- -----------------------------------------------------------------------------
-- 3b) In-app notifications (read by api/alerts.php, written by api/config.php)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.alerts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES public.users (id),
  title varchar(200) NOT NULL,
  message text NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'unread',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- created_at must be timestamptz, otherwise the browser renders UTC values as local time.
ALTER TABLE public.alerts
  ALTER COLUMN created_at TYPE timestamptz USING (created_at AT TIME ZONE 'UTC'),
  ALTER COLUMN created_at SET DEFAULT now(),
  ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE public.alerts DROP CONSTRAINT IF EXISTS alerts_status_chk;
ALTER TABLE public.alerts ADD CONSTRAINT alerts_status_chk CHECK (status IN ('unread', 'read'));

CREATE INDEX IF NOT EXISTS alerts_user_created_idx ON public.alerts (user_id, created_at DESC);

ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.alerts IS 'In-app notifications per user. RLS on; PHP service role reads and writes.';

-- -----------------------------------------------------------------------------
-- 3c) Forgot-password codes (emailed, then exchanged for a one-time reset token)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.password_resets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  code_hash text NOT NULL,
  reset_token_hash text,
  attempts integer NOT NULL DEFAULT 0,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_password_resets_user ON public.password_resets (user_id, created_at DESC);

ALTER TABLE public.password_resets ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.password_resets IS 'Hashed email codes and one-time reset tokens. PHP service role only.';

-- -----------------------------------------------------------------------------
-- 4) Audit / security events (login, role changes, contract decisions)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type text NOT NULL,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  actor_user_id bigint REFERENCES public.users (id) ON DELETE SET NULL,
  ip_address text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_event_type ON public.audit_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_user_id ON public.audit_logs (actor_user_id);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.audit_logs IS 'Technical audit trail: auth, admin actions, contract decisions. RLS on; PHP service role reads and writes.';
COMMENT ON COLUMN public.users.last_seen_at IS 'Updated on session heartbeat for defensible activity UI.';
COMMENT ON COLUMN public.users.last_login_at IS 'Updated on successful password login.';
COMMENT ON COLUMN public.users.password IS 'Stores password_hash output only. Plaintext complexity (8–64 chars, at least one letter and one number) is enforced in API/UI, not in Postgres.';
COMMENT ON COLUMN public.users.contact_number IS 'Required for vendor signup (PH mobile). Nullable for admin/manager/ceo staff created by admin.';
COMMENT ON COLUMN public.users.supplier_type IS 'Required for vendor signup: Supply, Lease, Service, or Other. Nullable for staff.';
COMMENT ON COLUMN public.users.company_name IS 'Vendor/supplier company shown on dashboards. Staff keep a personal name in users.name.';
COMMENT ON COLUMN public.users.terms_accepted_at IS 'Set once when the user agrees to the Terms & Conditions / Privacy Policy modal; NULL means the modal is still required at sign in.';
COMMENT ON COLUMN public.users.terms_version IS 'Version string of the terms the user agreed to (see CONTRACK_TERMS_VERSION in api/terms.php).';

-- -----------------------------------------------------------------------------
-- 7) AI / NLP usage log (extract + submit)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.nlp_usage (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES public.users (id) ON DELETE SET NULL,
  contract_id uuid REFERENCES public.vendor_contracts (id) ON DELETE SET NULL,
  source text NOT NULL,
  engine text NOT NULL,
  success boolean NOT NULL DEFAULT true,
  duration_ms integer,
  source_file_name text,
  input_kind text,
  input_chars integer,
  fields_filled jsonb NOT NULL DEFAULT '[]'::jsonb,
  clause_count integer NOT NULL DEFAULT 0,
  avg_confidence numeric(6,4),
  error_message text,
  ip_address text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT nlp_usage_source_chk CHECK (source IN ('extract', 'submit')),
  CONSTRAINT nlp_usage_engine_chk CHECK (engine IN ('python-ml', 'php-regex', 'unavailable')),
  CONSTRAINT nlp_usage_input_kind_chk CHECK (
    input_kind IS NULL OR input_kind IN ('pdf', 'text', 'pdf_and_text')
  )
);

CREATE INDEX IF NOT EXISTS nlp_usage_user_id_idx ON public.nlp_usage (user_id);
CREATE INDEX IF NOT EXISTS nlp_usage_contract_id_idx ON public.nlp_usage (contract_id);
CREATE INDEX IF NOT EXISTS nlp_usage_created_at_idx ON public.nlp_usage (created_at DESC);
CREATE INDEX IF NOT EXISTS nlp_usage_engine_idx ON public.nlp_usage (engine);

ALTER TABLE public.nlp_usage ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.nlp_usage IS 'AI/NLP extraction usage: who ran it, which engine, duration, and which fields were filled. Written by the PHP API with the service role.';

-- -----------------------------------------------------------------------------
-- 6) NLP / monitoring extras (idempotent)
-- -----------------------------------------------------------------------------
ALTER TABLE public.vendor_contracts
  ADD COLUMN IF NOT EXISTS renewal_terms text,
  ADD COLUMN IF NOT EXISTS penalty_clause text,
  ADD COLUMN IF NOT EXISTS financial_obligations text,
  ADD COLUMN IF NOT EXISTS classification text,
  ADD COLUMN IF NOT EXISTS is_archived boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS archived_at timestamptz,
  ADD COLUMN IF NOT EXISTS submission_text text,
  ADD COLUMN IF NOT EXISTS original_pdf_stored boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS contract_code text;

CREATE SEQUENCE IF NOT EXISTS public.vendor_contract_code_seq START WITH 1001;

UPDATE public.vendor_contracts
SET contract_code = 'CT-' || lpad(nextval('public.vendor_contract_code_seq')::text, 4, '0')
WHERE contract_code IS NULL OR btrim(contract_code) = '';

CREATE UNIQUE INDEX IF NOT EXISTS vendor_contracts_contract_code_uidx
  ON public.vendor_contracts (contract_code);

ALTER TABLE public.vendor_contracts
  ALTER COLUMN contract_code SET DEFAULT (
    'CT-' || lpad(nextval('public.vendor_contract_code_seq')::text, 4, '0')
  );

COMMENT ON COLUMN public.vendor_contracts.contract_code IS 'Short searchable id such as CT-1001. The uuid primary key stays internal.';

-- -----------------------------------------------------------------------------
-- 5) Signup credential CHECKs (idempotent: drop then add)
--    Password complexity cannot be checked after hashing; only non-empty hash.
-- -----------------------------------------------------------------------------
-- Normalize rows that would fail new CHECKs (spaces in phones, digits in names).
UPDATE public.users
SET contact_number = NULLIF(regexp_replace(btrim(contact_number), '\s+', '', 'g'), '')
WHERE contact_number IS NOT NULL
  AND contact_number IS DISTINCT FROM regexp_replace(btrim(contact_number), '\s+', '', 'g');

UPDATE public.users
SET contact_number = NULL
WHERE contact_number IS NOT NULL
  AND contact_number !~ '^(09[0-9]{9}|\+639[0-9]{9}|639[0-9]{9})$';

UPDATE public.users
SET supplier_type = NULL
WHERE supplier_type IS NOT NULL
  AND supplier_type NOT IN ('Supply', 'Lease', 'Service', 'Other');

UPDATE public.users
SET name = 'User'
WHERE char_length(btrim(name)) < 2
   OR char_length(btrim(name)) > 120
   OR btrim(name) ~ '[[:cntrl:]]';

UPDATE public.users
SET email = lower(btrim(email))
WHERE email IS DISTINCT FROM lower(btrim(email));

ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_name_format_chk;
ALTER TABLE public.users ADD CONSTRAINT users_name_format_chk CHECK (
  char_length(btrim(name)) BETWEEN 2 AND 120
  AND btrim(name) !~ '[[:cntrl:]]'
);

ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_company_name_chk;
ALTER TABLE public.users ADD CONSTRAINT users_company_name_chk CHECK (
  company_name IS NULL
  OR (
    char_length(btrim(company_name)) BETWEEN 2 AND 120
    AND btrim(company_name) !~ '[[:cntrl:]]'
  )
);

ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_email_format_chk;
ALTER TABLE public.users ADD CONSTRAINT users_email_format_chk CHECK (
  char_length(email) <= 254
  AND position('@' IN email) > 1
);

ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_contact_number_ph_chk;
ALTER TABLE public.users ADD CONSTRAINT users_contact_number_ph_chk CHECK (
  contact_number IS NULL
  OR contact_number ~ '^(09[0-9]{9}|\+639[0-9]{9}|639[0-9]{9})$'
);

ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_supplier_type_chk;
ALTER TABLE public.users ADD CONSTRAINT users_supplier_type_chk CHECK (
  supplier_type IS NULL
  OR supplier_type IN ('Supply', 'Lease', 'Service', 'Other')
);

ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_password_hash_present_chk;
ALTER TABLE public.users ADD CONSTRAINT users_password_hash_present_chk CHECK (
  char_length(btrim(password)) > 0
);

-- -----------------------------------------------------------------------------
-- 8) Manual vendor scoring (evaluations are stored; scores are never predicted)
--    Vendors are rows in public.users (role vendor/client), not public.vendors.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.vendor_score_criteria (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  name text NOT NULL,
  description text,
  weight numeric(6,4) NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT vendor_score_criteria_code_unique UNIQUE (code),
  CONSTRAINT vendor_score_criteria_weight_chk CHECK (weight > 0 AND weight <= 1),
  CONSTRAINT vendor_score_criteria_code_chk CHECK (code ~ '^[a-z][a-z0-9_]{1,40}$')
);

CREATE TABLE IF NOT EXISTS public.vendor_evaluations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vendor_id integer NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
  evaluator_id integer NOT NULL REFERENCES public.users (id) ON DELETE RESTRICT,
  evaluated_at timestamptz NOT NULL DEFAULT now(),
  overall_score numeric(6,2) NOT NULL,
  rating text NOT NULL,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT vendor_evaluations_score_chk CHECK (overall_score >= 0 AND overall_score <= 100),
  CONSTRAINT vendor_evaluations_rating_chk CHECK (
    rating IN ('excellent', 'good', 'satisfactory', 'needs_improvement')
  ),
  CONSTRAINT vendor_evaluations_remarks_chk CHECK (remarks IS NULL OR char_length(remarks) <= 2000)
);

CREATE TABLE IF NOT EXISTS public.vendor_evaluation_scores (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  evaluation_id uuid NOT NULL REFERENCES public.vendor_evaluations (id) ON DELETE CASCADE,
  criterion_id bigint NOT NULL REFERENCES public.vendor_score_criteria (id) ON DELETE RESTRICT,
  score numeric(6,2) NOT NULL,
  weighted_score numeric(8,4) NOT NULL,
  CONSTRAINT vendor_evaluation_scores_unique UNIQUE (evaluation_id, criterion_id),
  CONSTRAINT vendor_evaluation_scores_score_chk CHECK (score >= 0 AND score <= 100)
);

CREATE INDEX IF NOT EXISTS vendor_evaluations_vendor_evaluated_idx
  ON public.vendor_evaluations (vendor_id, evaluated_at DESC);
CREATE INDEX IF NOT EXISTS vendor_evaluations_evaluator_idx
  ON public.vendor_evaluations (evaluator_id);

ALTER TABLE public.vendor_score_criteria ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendor_evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendor_evaluation_scores ENABLE ROW LEVEL SECURITY;

INSERT INTO public.vendor_score_criteria (code, name, description, weight, sort_order)
VALUES
  ('quality', 'Quality of goods / services', 'Accuracy, workmanship, and whether deliverables meet the contracted specification.', 0.2000, 10),
  ('delivery', 'Delivery / timeliness', 'On-time performance against agreed milestones and delivery dates.', 0.2000, 20),
  ('compliance', 'Compliance & documentation', 'Adherence to contract terms, permits, and complete supporting documents.', 0.2000, 30),
  ('pricing', 'Pricing competitiveness', 'Value for money relative to scope, quality, and market rates.', 0.1500, 40),
  ('communication', 'Communication & responsiveness', 'Clarity, availability, and how quickly issues are resolved.', 0.1500, 50),
  ('innovation', 'Innovation / value-add', 'Process improvements or extras that reduce cost or risk for the company.', 0.1000, 60)
ON CONFLICT (code) DO NOTHING;
